# Generated by Django 3.2.7 on 2021-10-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0004_response_game'),
        ('games', '0002_remove_gameresult_responses'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='responses',
            field=models.ManyToManyField(to='nomenclatures.Response'),
        ),
    ]
