# Generated by Django 3.2.7 on 2021-10-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_gameresult_earned_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
