# Generated by Django 3.2.7 on 2021-10-08 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nomenclatures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='valid_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='valid_questions', to='nomenclatures.answerchoice'),
        ),
        migrations.AddField(
            model_name='question',
            name='valid_strict_answer',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='_questions', to='nomenclatures.AnswerChoice'),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('question', models.CharField(max_length=300)),
                ('strict_response', models.BooleanField(null=True)),
                ('choice_response', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.answerchoice')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Editor')),
            ],
            options={
                'db_table': 'responses',
                'ordering': ['id'],
            },
        ),
    ]
